
# THIS FILE IS GENERATED FROM SETUP.PY
SHORT_VERSION = '0.0.0'
VERSION = '0.0.0'
FULL_VERSION = '0.0.0.dev-Unknown'
GIT_REVISION = 'Unknown'
RELEASE = False

if not RELEASE:
    VERSION = FULL_VERSION
